<!DOCTYPE html>
<html lang="en-US">
<html>
<head>
	<title>CV Creation Software</title>
	<link rel="stylesheet" href="css/login.css">
</head>
<body>
	<h1><a href = "Index.PHP">CV Creation Software</a></h1>
	<h2>Welcome</h2>
	<h3><a href = "TemplatePreview.PHP">View Templates</a></h3>
	<h3><a href = "UploadTemplate.PHP">Upload Templates</a></h3>
	<h3><a href = "CVInfoInput.PHP">Create CV</a></h3>
	<p><a href = "Logout.PHP">Logout</a></p>
</body>
</html>